name: ingilizce_destek_app
description: "İngilizce Arkadaşım - Mobil Eğitim Uygulaması."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0
  cloud_firestore: ^6.1.3
  google_fonts: ^8.0.2
  flip_card: ^0.7.0
  flutter_tts: ^4.2.5
  translator: ^1.0.4+1
  youtube_player_flutter: ^9.1.3
  http: ^1.6.0
  lottie: ^2.6.0
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0 # Bunu ekle
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.13.1" # İkon üretici buraya taşındı
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png # Uygulama içi (Splash/Auth) logomuz

# --- TELEFON ANA EKRAN İKONU AYARLARI ---
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png" # Dışarıda görünecek devasa ve sade ikon
  adaptive_icon_background: "#4527A0" # YENİ: Çemberi tamamen dolduracak Koyu Mor renk!
  adaptive_icon_foreground: "assets/logo_seffaf.png" # YENİ: Morun üzerine binecek şeffaf baykuş

flutter_native_splash:
  color: "#F8FAFF" # Uygulamanın arka plan rengi
  image: "assets/logo.png" # İçerideki detaylı logomuz!
  android_12:
    color: "#F8FAFF"
    image: "assets/logo.png"