// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYtb48WMKHjHitwTK9mEE-Oby9lIpep80',
    appId: '1:689751965790:web:ba83f7654d55355845f4cf',
    messagingSenderId: '689751965790',
    projectId: 'ingilizce-destek-app',
    authDomain: 'ingilizce-destek-app.firebaseapp.com',
    storageBucket: 'ingilizce-destek-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-gfod3FHdQy3_fVQAWbeskxkya39WVxM',
    appId: '1:689751965790:android:cd9a1b910483862845f4cf',
    messagingSenderId: '689751965790',
    projectId: 'ingilizce-destek-app',
    storageBucket: 'ingilizce-destek-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxFp8PBS6JotvWWXbmejsB0P8OJaNZeqg',
    appId: '1:689751965790:ios:8e562f448f673d2c45f4cf',
    messagingSenderId: '689751965790',
    projectId: 'ingilizce-destek-app',
    storageBucket: 'ingilizce-destek-app.firebasestorage.app',
    iosBundleId: 'com.example.ingilizceDestekApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxFp8PBS6JotvWWXbmejsB0P8OJaNZeqg',
    appId: '1:689751965790:ios:8e562f448f673d2c45f4cf',
    messagingSenderId: '689751965790',
    projectId: 'ingilizce-destek-app',
    storageBucket: 'ingilizce-destek-app.firebasestorage.app',
    iosBundleId: 'com.example.ingilizceDestekApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYtb48WMKHjHitwTK9mEE-Oby9lIpep80',
    appId: '1:689751965790:web:c22e7bd617878dc045f4cf',
    messagingSenderId: '689751965790',
    projectId: 'ingilizce-destek-app',
    authDomain: 'ingilizce-destek-app.firebaseapp.com',
    storageBucket: 'ingilizce-destek-app.firebasestorage.app',
  );
}
